/// Firebase configuration options.
///
/// Generated by FlutterFire CLI. Run the following command to regenerate:
///
/// ```bash
/// flutterfire configure
/// ```
///
/// This file is intentionally left as a placeholder until Firebase is
/// initialized in the Firebase Console and `flutterfire configure` is executed.
library;
