// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJnHAIYBcEz2sAcULCiEYdczxA-J7z8DA',
    appId: '1:174114586214:web:f9eb00f4fe7ee52d86f7a7',
    messagingSenderId: '174114586214',
    projectId: 'silverworker-d8d64',
    authDomain: 'silverworker-d8d64.firebaseapp.com',
    storageBucket: 'silverworker-d8d64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwq7HeWW6lhmprG4wEDDzuxA3Q67J2_0Y',
    appId: '1:174114586214:android:c952a4bad9232ad886f7a7',
    messagingSenderId: '174114586214',
    projectId: 'silverworker-d8d64',
    storageBucket: 'silverworker-d8d64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw0augX_FhkXsMYgjbrHMr1n2lEtNxKBE',
    appId: '1:174114586214:ios:c78ac369034a60f286f7a7',
    messagingSenderId: '174114586214',
    projectId: 'silverworker-d8d64',
    storageBucket: 'silverworker-d8d64.firebasestorage.app',
    iosBundleId: 'com.silverworkernow.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw0augX_FhkXsMYgjbrHMr1n2lEtNxKBE',
    appId: '1:174114586214:ios:d9d0ce4791004adc86f7a7',
    messagingSenderId: '174114586214',
    projectId: 'silverworker-d8d64',
    storageBucket: 'silverworker-d8d64.firebasestorage.app',
    iosBundleId: 'com.silverworkernow.app.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJnHAIYBcEz2sAcULCiEYdczxA-J7z8DA',
    appId: '1:174114586214:web:5576f675850c0cd586f7a7',
    messagingSenderId: '174114586214',
    projectId: 'silverworker-d8d64',
    authDomain: 'silverworker-d8d64.firebaseapp.com',
    storageBucket: 'silverworker-d8d64.firebasestorage.app',
  );
}
